name: Build ALL
run-name: Build ALL

on:
  workflow_dispatch:
    inputs:
      build_macos:
        description: 'Build MacOS'
        required: true
        default: true
        type: boolean
      build_ios:
        description: 'Build iOS'
        required: true
        default: true
        type: boolean
      build_android:
        description: 'Build Android'
        required: true
        default: true
        type: boolean
      build_windows:
        description: 'Build Windows'
        required: true
        default: true
        type: boolean
      build_linux:
        description: 'Build Linux'
        required: true
        default: true
        type: boolean
      build_linux_arm64:
        description: 'Build Linux ARM64'
        required: true
        default: true
        type: boolean

  release:
    types: [published]


jobs:

  Build_MacOS:
    if: ${{ inputs.build_macos }}
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          architecture: x64

      - run: sudo xcode-select --switch /Applications/Xcode_16.4.app
      - run: flutter pub get

      - name: Build
        run: flutter build macos --release

      - name: Create DMG
        run: |
          mkdir -p dist/dmg_contents
          cp -R build/macos/Build/Products/Release/venera.app dist/dmg_contents/
          ln -s /Applications dist/dmg_contents/Applications
          hdiutil create \
            -volname "venera" \
            -srcfolder dist/dmg_contents \
            -ov \
            -format UDZO \
            dist/venera.dmg

      - uses: actions/upload-artifact@v4
        with:
          name: macos_build
          path: dist/venera.dmg


  Build_IOS:
    if: ${{ inputs.build_ios }}
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - run: sudo xcode-select --switch /Applications/Xcode_16.4.app
      - run: flutter pub get

      - run: flutter build ios --release --no-codesign

      - run: |
          mkdir -p build/ios/iphoneos/Payload
          mv build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/
          cd build/ios/iphoneos
          zip -r venera-ios.ipa Payload

      - uses: actions/upload-artifact@v4
        with:
          name: ios_build
          path: build/ios/iphoneos/venera-ios.ipa


  Build_Android:
    if: ${{ inputs.build_android }}
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4


      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          architecture: x64


      - uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: 17


      # 生成临时签名
      - name: Generate fake android keystore
        run: |
          mkdir -p android

          keytool \
          -genkeypair \
          -v \
          -keystore android/debug.keystore \
          -alias androiddebugkey \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -storepass android \
          -keypass android \
          -dname "CN=Android Debug,O=Android,C=US"


      - name: Create signing config
        run: |
          cat > android/key.properties <<EOF
          storeFile=debug.keystore
          storePassword=android
          keyAlias=androiddebugkey
          keyPassword=android
          EOF


      - run: flutter pub get


      - name: Build Android APK
        run: flutter build apk --release


      - uses: actions/upload-artifact@v4
        with:
          name: apks
          path: build/app/outputs/apk/release



  Build_Windows:
    if: ${{ inputs.build_windows }}
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          choco install yq innosetup -y
          pip install httpx

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - run: |
          flutter pub get
          python windows/build.py

      - uses: actions/upload-artifact@v4
        with:
          name: windows_build
          path: build/windows/Venera-*



  Build_Linux:
    if: ${{ inputs.build_linux }}
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml


      - run: |
          sudo apt update
          sudo apt install -y ninja-build libgtk-3-dev webkit2gtk-4.1
          dart pub global activate -s git https://github.com/venera-app/flutter_to_debian.git


      - run: python3 debian/build.py x64
      - run: dart run flutter_to_arch


      - uses: actions/upload-artifact@v4
        with:
          name: deb_build
          path: build/linux/x64/release/debian


      - uses: actions/upload-artifact@v4
        with:
          name: arch_build
          path: build/linux/arch



  Build_Linux_ARM64:
    if: ${{ inputs.build_linux_arm64 }}
    runs-on: ubuntu-22.04-arm

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: master
          flutter-version-file: pubspec.yaml


      - run: |
          flutter pub get
          sudo apt update
          sudo apt install -y ninja-build libgtk-3-dev webkit2gtk-4.1
          dart pub global activate -s git https://github.com/venera-app/flutter_to_debian.git


      - run: python3 debian/build.py arm64


      - uses: actions/upload-artifact@v4
        with:
          name: deb_arm64_build
          path: build/linux/x64/release/debian



  Release:
    runs-on: ubuntu-22.04

    needs:
      - Build_MacOS
      - Build_IOS
      - Build_Android
      - Build_Windows
      - Build_Linux
      - Build_Linux_ARM64

    if: github.event_name == 'release'

    steps:

      - uses: actions/download-artifact@v4
        with:
          path: outputs


      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            outputs/**/*.ipa
            outputs/**/*.dmg
            outputs/**/*.apk
            outputs/**/*.exe
            outputs/**/*.deb
            outputs/**/*.zst
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
